---
name: ssh-userpass

provides:
  tech:
    - entry:
        name: ssh
        version:
        config:
          - name: username:password
            file: userpass_script.sh
            value:
            - nader:pass
            - max:muster


needs:
  tech:
    - entry:
        name: ssh
        version:
        config:
          - name: PORT_FORWARDING
            file: main.sh
            value:
            - "2200"
