---
name: log-poison

provides:
  tech:
    - entry:
        name: php
        version: "7.2"
        config:
          - name: PHP_PORT_FORWARDING
            file: main.sh
            value:
              - "8800"


needs:
  tech:
    - entry:
        name: ssh
        config:
          - name: SSH_PORT
            file: main.sh
            value:
              - "2200"
